Free disk space before start build
Signed-off-by: asd1115056 <asd1115056@gmail.com>

diff --git a/.github/workflows/ct-ng-build.yml b/.github/workflows/ct-ng-build.yml
--- a/.github/workflows/ct-ng-build.yml
+++ b/.github/workflows/ct-ng-build.yml
@@ -41,5 +41,19 @@ jobs:
       - name: Ensure script is executable
         run: chmod +x ./Build_image.sh
 
+      - name: Free disk space
+        run: |
+          # https://github.com/jlumbroso/free-disk-space
+          set -ex
+          sudo rm -rf /usr/local/lib/android || true
+          sudo rm -rf /usr/share/dotnet || true
+          sudo rm -rf /opt/ghc || true
+          sudo rm -rf /usr/local/.ghcup || true
+          sudo docker image prune --all --force || true
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
+
+          # Display disk usage after cleanup
+          df -h
+
       - name: Build and Push Docker image
         run: ./Build_image.sh -c "${{ matrix.config }}" -m push
